language: objective-c

notifications:
  email:
    on_success: never
    on_failure: change

script: 'curl -s https://raw.githubusercontent.com/michaelaquilina/python-tools/master/build-package.sh | sh'
